name: SimplyPronouns
version: '${version}'
main: org.lushplugins.simplypronouns.SimplyPronouns
api-version: '1.20'
authors:
  - OakLoaf
commands:
  pronouns:
    usage: /pronouns <pronouns>
  checkpronouns:
    usage: /checkpronouns <player>